### ISSUE TITLE
Verifying a remote host

### ISSUE THREAD

**Issue by tigerw** [FlexyProject/GitHubAPI#35]
I noted that when making a request in AbstractApi, `VERIFYPEER` and `VERIFYHOST` are explicitly disabled. I understand that this is not recommended practice.

Is this intended functionality? Perhaps a solution of providing a means to set the certificate bundle location, and thus have cURL perform this verification will be more robust.

**Comment by emulienfou** [comment]
According to some posts you right, this 2 values must not be disabled. I just fix it!

Here is what we can find in the official documentation of PHP:

> Please everyone, stop setting `CURLOPT_SSL_VERIFYPEER` to `false` or `0`. If your PHP installation doesn't have an up-to-date CA root certificate bundle, download the one at the curl website and save it on your server:

> http://curl.haxx.se/docs/caextract.html

> Then set a path to it in your php.ini file, e.g. on Windows:

> curl.cainfo=c:\php\cacert.pem

> Turning off `CURLOPT_SSL_VERIFYPEER` allows man in the middle (MITM) attacks, which you don't want!

This is the same for the `CURLOPT_SSL_VERIFYHOST`.
