### ISSUE TITLE
Potential headers overwriting

### ISSUE THREAD

**Issue by tigerw** [FlexyProject/GitHubAPI#41]
It seems like with OAuth2 header authentication, [this line](https://github.com/FlexyProject/GitHubAPI/blob/1.1/AbstractApi.php#L408) will set a cURL header option which overwrites headers initially set [here](https://github.com/FlexyProject/GitHubAPI/blob/1.1/AbstractApi.php#L364). This renders calls to `setAccept` and `setContentType` non-functional, since their contents are never sent.

**Comment by emulienfou** [comment]
Updating cURL dependency, see: https://github.com/FlexyProject/Curl/releases/tag/1.1.3
